# Generated by Django 4.2 on 2023-09-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceinfield',
            old_name='analyzer_id',
            new_name='analyzer',
        ),
        migrations.RenameField(
            model_name='deviceinfield',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.TextField(choices=[('open', 'відкрита'), ('closed', 'закрита'), ('in progress', 'в роботі'), ('need info', 'потрібна інформація')], verbose_name='Статус заявки'),
        ),
    ]
